Remove build hack
mapfish/mapfish-print pull request #2885
Opened 2023-03-29 07:33 UTC by sbrunner

The idea of removing checkstyle is to replace it by a pre-commit hook that applies the Google code style:
see: https://github.com/macisamuele/language-formatters-pre-commit-hooks

2023-04-04 14:24 UTC, sbrunner commented on Makefile
> +	docker run --rm --detach \
don't use --detach

2023-04-04 14:27 UTC, sbrunner commented on Makefile
> +profile: build-builder ## Profile a task
The result will be in build/report

2023-04-04 14:28 UTC, sbrunner commented on Makefile
> +	docker cp print-builder:/src/build/reports/ build/
missing docker stop print-builder

2023-05-08 08:44 UTC, sbrunner commented
We should keep check style...

2023-05-31 07:33 UTC, sebr72 commented on .github/workflows/main.yaml
> -      - uses: actions/upload-artifact@v3
As discussed please reintroduce the 4 CI artifacts

2023-05-31 07:39 UTC, sbrunner commented on Dockerfile
> +   :core:build :core:explodedWar :publish:build :examples:build buildDocs
`core:explodedWar` is steel needed...
Others done :-)

2023-06-05 07:58 UTC, sebr72 requested changes

2023-06-05 07:58 UTC, sebr72 commented on core/src/main/java/org/mapfish/print/HumanAlphaSerie.java
Let's move this to a sub-package like jasperreports

2023-06-05 08:04 UTC, sebr72 approved these changes
Approved pending requested jasperreports package creation

2023-06-05 09:16 UTC, merged