Try max distance to 0
mapfish/mapfish-print pull request #3136
Opened 2023-12-13 16:59 UTC by sbrunner

2024-01-12 11:54 UTC, sebr72 requested changes

2024-01-12 11:54 UTC, sebr72 commented on examples/src/test/resources/examples/simple/expected_output/requestData-fontawesome.png
Check if easy to modify Countries to Fontawesome

2024-01-12 11:54 UTC, sebr72 commented on core/src/main/java/org/mapfish/print/map/image/ImageLayer.java
> +    } catch (Exception e) {
please catch only the 2 exceptions from fetchImage and RuntimeException if required

2024-01-12 11:54 UTC, sebr72 commented on core/src/main/java/org/mapfish/print/map/image/ImageLayer.java
> +    if (imageBufferScaling >= 2) {
Please choose between removing or adding a config parameter to enable this feature, and include a test to show behaviour.

2024-01-15 16:50 UTC, sbrunner commented on examples/src/test/resources/examples/printwms_tyger_ny_EPSG_3857/expected_output/requestData-multi-layer-openlayers-2-compatible-style-wms.png
It's the pixel of the `nurc:Img_Sample` layer :-)

2024-01-17 12:49 UTC, sebr72 approved these changes

2024-01-17 14:48 UTC, merged