Use getRawStatusCode to don't get an exception on fake status code 999
mapfish/mapfish-print pull request #3497
Opened 2024-11-01 08:34 UTC by sbrunner

2024-11-01 10:05 UTC, gberaudo approved these changes

2024-11-01 11:39 UTC, sebr72 requested changes
Please use 406 status code and add test

2024-11-01 15:28 UTC, sebr72 commented on core/src/main/java/org/mapfish/print/map/tiled/CoverageTask.java
> +        final int statusCode, final ClientHttpResponse response, final String baseMetricName)
Need to adapt Log messages below

2024-11-01 15:31 UTC, sebr72 commented on core/src/main/java/org/mapfish/print/map/tiled/CoverageTask.java
>          return handleNonOkStatus(statusCode, response, baseMetricName);
Validate status code is redundant then remove it

2024-11-01 15:33 UTC, sebr72 commented on core/src/main/java/org/mapfish/print/map/image/AbstractSingleImageLayer.java
> +              "Invalid status code for %s (%d!=%d), status: %s. With request headers:\n%s\n"
update log %s

2024-11-03 02:16 UTC, sebr72 approved these changes

2024-11-04 07:56 UTC, sbrunner commented
Is it ready to be merged?

2024-11-04 08:10 UTC, sebr72 commented
@sbrunner If you are satisfied with my changes. Please go ahead with the merge.

2024-11-04 08:43 UTC, merged